import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { useAuthStore } from '../store/auth'

type Internship = { id: number; title: string; description: string; location: string; industry: string; duration_months: number; stipend?: number; work_mode: string; skills: string[]; deadline: string; status: string; company_name?: string }
const auth = () => ({ headers: { Authorization: `Bearer ${useAuthStore.getState().session?.accessToken}` } })

export function InternshipListingPage() {
  const [items, setItems] = useState<Internship[]>([]); const [filters, setFilters] = useState({ location: '', industry: '', work_mode: '', skills: '' }); const [page, setPage] = useState(1)
  useEffect(() => { api.get('/internships', { params: { ...filters, page, page_size: 12 }, ...auth() }).then(response => setItems(response.data.items)) }, [filters, page])
  return <section className="listing"><aside className="filter-sidebar"><p className="eyebrow">Discover</p><h2>Find your next move.</h2>{Object.keys(filters).map(key => <label key={key}>{key.replace('_', ' ')}<input value={filters[key as keyof typeof filters]} onChange={event => { setPage(1); setFilters({ ...filters, [key]: event.target.value }) }} /></label>)}<select value={filters.work_mode} onChange={event => setFilters({ ...filters, work_mode: event.target.value })}><option value="">Any work mode</option><option>REMOTE</option><option>HYBRID</option><option>ONSITE</option></select></aside><div className="results"><p className="eyebrow">Published internships</p>{items.map(item => <Link className="internship-item" to={`/internships/${item.id}`} key={item.id}><span>{item.company_name || item.industry} · {item.work_mode}</span><h2>{item.title}</h2><p>{item.location} · {item.duration_months} months{item.stipend ? ` · ${item.stipend} stipend` : ''}</p></Link>)}<div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button onClick={() => setPage(page + 1)}>Next</button></div></div></section>
}

export function InternshipDetailPage() { const { id } = useParams(); const [item, setItem] = useState<Internship>(); const [message, setMessage] = useState(''); useEffect(() => { api.get(`/internships/${id}`, auth()).then(response => setItem(response.data)) }, [id]); async function apply() { try { await api.post(`/applications/internships/${id}`, {}, auth()); setMessage('Application submitted.') } catch { setMessage('Unable to submit application.') } } if (!item) return <section className="welcome"><p>Loading internship...</p></section>; return <section className="welcome"><p className="eyebrow">{item.company_name ? `${item.company_name} · ` : ''}{item.industry} · {item.work_mode}</p><h1>{item.title}</h1><p className="intro">{item.description}</p><p className="intro">{item.location} · {item.duration_months} months · Deadline {item.deadline}</p><p>{item.skills.join(' · ')}</p><button className="primary-action" onClick={apply}>Apply now</button>{message && <p className="form-message">{message}</p>}</section> }

export function InternshipFormPage() { const navigate = useNavigate(); const { id } = useParams(); const [message, setMessage] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); form.duration_months = String(form.duration_months); form.stipend = String(form.stipend || ''); form.skills = String(form.skills || '').split(',').map(value => value.trim()).filter(Boolean) as unknown as string; try { const response = id ? await api.put(`/internships/${id}`, form, auth()) : await api.post('/internships', form, auth()); setMessage(`Saved as ${response.data.status}.`); if (!id) navigate(`/company/internships/${response.data.id}/edit`) } catch { setMessage('Unable to save internship.') } } return <section className="auth-panel"><p className="eyebrow">Company workspace</p><h1>{id ? 'Edit internship' : 'Create internship'}</h1><form onSubmit={submit}><label>Title<input name="title" required /></label><label>Description<textarea name="description" required /></label><label>Location<input name="location" required /></label><label>Industry<input name="industry" required /></label><label>Duration months<input name="duration_months" type="number" min="1" required /></label><label>Stipend<input name="stipend" type="number" min="0" /></label><label>Work mode<select name="work_mode"><option>REMOTE</option><option>HYBRID</option><option>ONSITE</option></select></label><label>Skills<input name="skills" placeholder="python, design, research" /></label><label>Deadline<input name="deadline" type="date" required /></label><button className="primary-action" type="submit">Save draft</button>{message && <p className="form-message">{message}</p>}</form></section> }
